name: 'Check PR'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  check-pr:
    runs-on: 'ubuntu-latest'
    name: Check Styles using Rome
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - uses: rome/setup-rome@v0.4
        with:
          version: latest
      - run: rome ci .
      - uses: actions/setup-node@v3
        with:
           node-version: 16
      - run: npm ci
      - run: npm run test